#include "types.h"
#include "versatilepb_pl190_vic.h"
#include "uart.h"
#include "vid.h"

extern UART uart[4];
extern void uart_handler(UART *up);

extern void uprints(UART *up, u8 *s);
extern void ugets(UART *up, char *s);

/* 
Use the nm on the image.o to check the actual symobl names exported.
If you are converting a "image.bmp" to "image.o", the symbol name will be "_binary_image_bmp_start".
Note that the file suffix will also be part of the exported symbol name.
*/

extern char _binary_image_bmp_start;
void show_bmp(u8 *p, u32 start_row, u32 start_col);

void main()
{
    u8 *p;
    u8 line[128];
    UART *up;
    VIC_INTENABLE |= UART0_IRQ_VIC_BIT;
    VIC_INTENABLE |= UART1_IRQ_VIC_BIT;

    uart_init();
    up= &uart[0];
    fbuf_init();
    p = &_binary_image_bmp_start; // symbol generated by the linker based on the input file name

    
    while(1)
    {
        uprints(up, "Enter a line from UART:\n\r");
        ugets(up, line);
        show_bmp(p, 0, 0);
        uprints(up, "You have entered below line from UART:\n\r");
        uprints(up, line);
    }
}

void copy_vectors()
{
    extern u32 vectors_start, vectors_end;
    u32 *vectors_src = &vectors_start;
    u32 *vectors_dst = (u32 *)0;
    while(vectors_src < &vectors_end)
    {
        *vectors_dst++ = *vectors_src++;
    }
}

void IRQ_handler()
{
    u32 vicstatus = VIC_STATUS;

    //UART 0
    if(vicstatus & UART0_IRQ_VIC_BIT)
    {
        uart_handler(&uart[0]);
    }

    //UART 1
    if(vicstatus & UART1_IRQ_VIC_BIT)
    {
        uart_handler(&uart[1]);
    }

}

void show_bmp(u8 *p, u32 start_row, u32 start_col)
{
    u32 h, w, pixel, rsize, i, j;
    u8 r, g, b;
    u8* pp;
    u32 *q =(u32 *)(p+14); //skip over 14-byte file header
    w = *(q+1); // image width in pixels
    h = *(q+2); // image height in pixels
    p += 54; // p points to pixels in image

    //BMP iamge is upside down, each row is a multiple of 4 bytes
    rsize = 4*((3*w+3)/4); //multiple of 4
    p += (h-1) * rsize; // last row of pixels
    for(i = start_row; i<start_row + h; i++)
    {
        pp=p;
        for(j=start_col;j<start_col+w;j++)
        {
            b=*pp;
            g=*(pp+1);
            r=*(pp+2);
            pixel = (b<<16)|(g<<8)|r;
            fb[i*WIDTH + j]=pixel;
            pp +=3; //advance pp to next pixel
        }
        p -=rsize; // to preceding row
    }
}