#include "types.h"
#include "versatilepb.h"

void main()
{
    u8 *p;
    u8 line[128];
    UART *up;
    VIC_INTENABLE |= UART0_IRQ_VIC_BIT;
    VIC_INTENABLE |= UART1_IRQ_VIC_BIT;

    uart_init();
    up= &uart[0];
    fbuf_init();
    p = &_binary___resource_images_image_bmp_start; // symbol generated by the linker based on the input file name
    u8* pLine = NULL;
    //show_bmp(p, 0, 0);// show the image at the screen location (0,0)
    u8 c = ' ';
    while(1)
    {
        if(gDisplayContext.cursor_row == gDisplayContext.max_row)
        {
            uprints(up, "[Input something through UART and then press Enter to show some chars:]\n\r");
            ugets(up, line);
            uprints(up, "[And you have entered below line from UART:]\n\r");
            uprints(up, line);
            pLine = &line[0];
            while(*pLine)
            {
                kputc(*pLine);
                pLine++;
            }

        }
        else
        {
            kputc(c);
            c = (c+1>'~')?' ':c+1;  
        }
    }
}

void copy_vectors()
{
    extern u32 vectors_start, vectors_end;
    u32 *vectors_src = &vectors_start;
    u32 *vectors_dst = (u32 *)0;
    while(vectors_src < &vectors_end)
    {
        *vectors_dst++ = *vectors_src++;
    }
}

void IRQ_handler()
{
    u32 vicstatus = VIC_STATUS;

    //UART 0
    if(vicstatus & UART0_IRQ_VIC_BIT)
    {
        uart_handler(&uart[0]);
    }

    //UART 1
    if(vicstatus & UART1_IRQ_VIC_BIT)
    {
        uart_handler(&uart[1]);
    }

}
